name: Bump version number
on:
  push:
    branches: ["master"]

# run only single workflow of this type at a time
concurrency: release

jobs:
  bump-version:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Append commit hash to changelog
        run: git rev-parse HEAD >> CHANGELOG.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Optional. Local and remote branch name where commit is going to be pushed
          #  to. Defaults to the current branch.
          #  You might need to set `create_branch: true` if the branch does not exist.
          branch: master

          # Optional. Options used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: "--no-verify --no-edit --amend"

          # Optional. Options used by `git-add`.
          # See https://git-scm.com/docs/git-add#_options
          add_options: "CHANGELOG.md"

          # Optional. Options used by `git-push`.
          # See https://git-scm.com/docs/git-push#_options
          push_options: "--force-with-lease"
